"""add analytics tables and refresh_tokens

Revision ID: 3fbbbb8f6b4b
Revises: 719fd6883ebd
Create Date: 2026-05-07 06:47:45.172520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbbbb8f6b4b'
down_revision: Union[str, Sequence[str], None] = '719fd6883ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_analytics',
    sa.Column('recruiter_id', sa.Uuid(), nullable=False),
    sa.Column('open_vacancies_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_candidates_assigned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('recruiter_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('vacancy_analytics',
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('total_candidates', sa.Integer(), server_default='0', nullable=False),
    sa.Column('days_open', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id')
    )
    op.create_table('stage_analytics',
    sa.Column('vacancy_stage_id', sa.Uuid(), nullable=False),
    sa.Column('candidates_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_days_in_stage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_stage_id'], ['vacancy_stages.id'], ),
    sa.PrimaryKeyConstraint('vacancy_stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_analytics')
    op.drop_table('vacancy_analytics')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('recruiter_analytics')
    # ### end Alembic commands ###
