"""add cascade delete to emails foreign keys

Revision ID: 8472473deed8
Revises: 8dc1fda3c365
Create Date: 2026-05-11 12:13:54.892775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8472473deed8'
down_revision: Union[str, Sequence[str], None] = '8dc1fda3c365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emails_vacancy_id_fkey'), 'emails', type_='foreignkey')
    op.drop_constraint(op.f('emails_sent_by_fkey'), 'emails', type_='foreignkey')
    op.drop_constraint(op.f('emails_candidate_id_fkey'), 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'emails', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'emails', 'users', ['sent_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key(op.f('emails_candidate_id_fkey'), 'emails', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('emails_sent_by_fkey'), 'emails', 'users', ['sent_by'], ['id'])
    op.create_foreign_key(op.f('emails_vacancy_id_fkey'), 'emails', 'vacancies', ['vacancy_id'], ['id'])
    # ### end Alembic commands ###
